{% set name = "oxDNA-analysis-tools" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oxDNA_analysis_tools-{{ version }}.tar.gz
  sha256: 2de8c3ef94754970a23a69b4af6fa9b26d9ef564cd96e6dd45249fa6afca3456

build:
  skip: true  # [py<38]
  entry_points:
    - oat = oxDNA_analysis_tools.entry:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - numpy
    - cython
    - pip
  run:
    - python
    - scikit-learn >0.21.2
    - matplotlib-base >3.0.0
    - biopython >1.73
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - oxDNA_analysis_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sulcgroup/oxdna_analysis_tools
  summary: Python scripts and libraries for structural analysis of oxDNA simulations.
  license: 'GPL-3.0-or-later'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
